@echo off
echo Opening UAOS final launch rooms...
if exist "E:\keyboard-manager-clean\uaos-ai-factory\uaos-v2517-v2566-big-launch-train-16-final-owner-one-click-launch-room\01-owner-one-click-room\UAOS_FINAL_OWNER_ONE_CLICK_LAUNCH_ROOM.html" start "" "E:\keyboard-manager-clean\uaos-ai-factory\uaos-v2517-v2566-big-launch-train-16-final-owner-one-click-launch-room\01-owner-one-click-room\UAOS_FINAL_OWNER_ONE_CLICK_LAUNCH_ROOM.html"
if exist "E:\keyboard-manager-clean\uaos-ai-factory\uaos-v2067-v2116-big-launch-train-07-launch-super-portal\10-dashboards\UAOS_LAUNCH_SUPER_PORTAL.html" start "" "E:\keyboard-manager-clean\uaos-ai-factory\uaos-v2067-v2116-big-launch-train-07-launch-super-portal\10-dashboards\UAOS_LAUNCH_SUPER_PORTAL.html"
if exist "E:\keyboard-manager-clean\uaos-ai-factory\uaos-v2117-v2166-big-launch-train-08-public-candidate-assembly\01-site-candidate\index.html" start "" "E:\keyboard-manager-clean\uaos-ai-factory\uaos-v2117-v2166-big-launch-train-08-public-candidate-assembly\01-site-candidate\index.html"
if exist "E:\keyboard-manager-clean\uaos-ai-factory\uaos-v2267-v2316-big-launch-train-11-owner-final-handoff-binder\10-dashboards\UAOS_OWNER_FINAL_HANDOFF_BINDER_DASHBOARD.html" start "" "E:\keyboard-manager-clean\uaos-ai-factory\uaos-v2267-v2316-big-launch-train-11-owner-final-handoff-binder\10-dashboards\UAOS_OWNER_FINAL_HANDOFF_BINDER_DASHBOARD.html"
if exist "E:\keyboard-manager-clean\uaos-ai-factory\uaos-v2267-v2316-big-launch-train-11-owner-final-handoff-binder\02-opening-war-room\UAOS_OPENING_WAR_ROOM.html" start "" "E:\keyboard-manager-clean\uaos-ai-factory\uaos-v2267-v2316-big-launch-train-11-owner-final-handoff-binder\02-opening-war-room\UAOS_OPENING_WAR_ROOM.html"
if exist "E:\keyboard-manager-clean\uaos-ai-factory\uaos-v2317-v2366-big-launch-train-12-opening-day-rehearsal-signature-pack\10-dashboards\UAOS_OPENING_DAY_REHEARSAL_SIGNATURE_PACK_DASHBOARD.html" start "" "E:\keyboard-manager-clean\uaos-ai-factory\uaos-v2317-v2366-big-launch-train-12-opening-day-rehearsal-signature-pack\10-dashboards\UAOS_OPENING_DAY_REHEARSAL_SIGNATURE_PACK_DASHBOARD.html"
if exist "E:\keyboard-manager-clean\uaos-ai-factory\uaos-v2367-v2416-big-launch-train-13-final-local-rehearsal-evidence-pack\10-dashboards\UAOS_FINAL_LOCAL_REHEARSAL_EVIDENCE_DASHBOARD.html" start "" "E:\keyboard-manager-clean\uaos-ai-factory\uaos-v2367-v2416-big-launch-train-13-final-local-rehearsal-evidence-pack\10-dashboards\UAOS_FINAL_LOCAL_REHEARSAL_EVIDENCE_DASHBOARD.html"
if exist "E:\keyboard-manager-clean\uaos-ai-factory\uaos-v2467-v2516-big-launch-train-15-backup-acceptance-final-freeze\10-dashboards\UAOS_BACKUP_ACCEPTANCE_FINAL_FREEZE_DASHBOARD.html" start "" "E:\keyboard-manager-clean\uaos-ai-factory\uaos-v2467-v2516-big-launch-train-15-backup-acceptance-final-freeze\10-dashboards\UAOS_BACKUP_ACCEPTANCE_FINAL_FREEZE_DASHBOARD.html"
